### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by lightning02** [grim3212/Grim3212-Core#1]
Problem with world in chunk generation in the log in.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [HUG]

Time: 01/06/15 11.07
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
at net.minecraft.world.World.func_147465_d(World.java:800)
at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1170)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
at net.minecraft.world.World.func_72964_e(World.java:739)
at net.minecraft.world.World.func_147439_a(World.java:665)
at drzhark.mocreatures.entity.passive.MoCEntityBird.FindTreeTop(MoCEntityBird.java:121)
at drzhark.mocreatures.entity.passive.MoCEntityBird.FlyToNextTree(MoCEntityBird.java:199)
at drzhark.mocreatures.entity.passive.MoCEntityBird.func_70636_d(MoCEntityBird.java:398)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1890)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
at net.minecraft.world.World.func_72866_a(World.java:2643)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
at net.minecraft.world.World.func_72870_g(World.java:2596)
at net.minecraft.world.World.func_72939_s(World.java:2409)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Thread.java:745)

-- Head --
Stacktrace:
at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
at net.minecraft.world.World.func_147465_d(World.java:800)
at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1170)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
at net.minecraft.world.World.func_72964_e(World.java:739)

++++++ The same at different coordinates.

---- Minecraft Crash Report ----
// Don't do that.

Time: 01/06/15 14.17
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
	at net.minecraft.world.World.func_147465_d(World.java:800)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
	at net.minecraft.world.World.func_72964_e(World.java:739)
	at net.minecraft.world.World.func_147439_a(World.java:665)
	at net.minecraft.world.World.func_147460_e(World.java:1068)
	at net.minecraft.world.World.func_147459_d(World.java:1027)
	at net.minecraft.world.World.func_147444_c(World.java:988)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:844)
	at net.minecraft.world.World.func_147465_d(World.java:822)
	at net.minecraft.world.gen.feature.WorldGenerator.func_150516_a(SourceFile:33)
	at com.pam.harvestcraft.WorldGenPamFruitPalmTree.func_76484_a(WorldGenPamFruitPalmTree.java:116)
	at com.pam.harvestcraft.PamTreeGenerator.generateSurface(PamTreeGenerator.java:226)
	at com.pam.harvestcraft.PamTreeGenerator.generate(PamTreeGenerator.java:22)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at grim3212.mc.ttmultra.metalworks.BlockDerrick.func_149749_a(BlockDerrick.java:132)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
	at net.minecraft.world.World.func_147465_d(World.java:800)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:456)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_108_EventHandlerGC_populate_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.get(AsynchronousExecutor.java:165)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:341)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
	at net.minecraft.world.World.func_72964_e(World.java:739)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-268,90,79), Chunk: (at 4,5,15 in -17,4; contains blocks -272,0,64 to -257,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:665)
	at net.minecraft.world.World.func_147460_e(World.java:1068)
	at net.minecraft.world.World.func_147459_d(World.java:1027)
	at net.minecraft.world.World.func_147444_c(World.java:988)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:844)
	at net.minecraft.world.World.func_147465_d(World.java:822)
	at net.minecraft.world.gen.feature.WorldGenerator.func_150516_a(SourceFile:33)
	at com.pam.harvestcraft.WorldGenPamFruitPalmTree.func_76484_a(WorldGenPamFruitPalmTree.java:116)
	at com.pam.harvestcraft.PamTreeGenerator.generateSurface(PamTreeGenerator.java:226)
	at com.pam.harvestcraft.PamTreeGenerator.generate(PamTreeGenerator.java:22)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

**Comment by grim3212** [comment]
I don't think this is a problem with TTM. But I'll keep looking into it. This might be a problem with Galacticraft. It doesn't make sense to be TTM's fault during world generation since that is breaking the block.

**Comment by lightning02** [comment]
No derrick in the world, it is new! It happened when the server tried to generate the chunk.
Maybe something was corrupted in the folder or server plugin (?)
Well, i've ask to the owner of galacticraft and he tell me that is not him problem!

**Comment by grim3212** [comment]
Okay I guess I try and figure it out...

**Comment by grim3212** [comment]
What mods are you using because I can't seem to reproduce the error with just Galacticraft and TTM.

**Comment by lightning02** [comment]
The pack is just too big.. Anyway recreating the server folder the error does not occur.. I can't figure out why.
The plugins was killermoney, valut, towny, essential

**Comment by grim3212** [comment]
Something might have been corrupted I have no idea. Glad you figured it out though!

**Comment by lightning02** [comment]
I did not understand exactly what it was.. I just tried to reinstall everything on the server and no longer gave the error
